AplicacionWeb/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace AplicacionWeb.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AplicacionWeb/Controllers/VentaController.cs
using AplicacionWeb.Models;
using BLL.Interfaces;
using Entity;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Numerics;
using Microsoft.AspNetCore.Authorization;

namespace AplicacionWeb.Controllers
{
    [Authorize]
    public class VentaController : Controller
    {
        private readonly IVentaService _ventaService;
        private readonly ITipoDocumentoVentaService _tipoDocService;

        public VentaController(IVentaService ventaService, ITipoDocumentoVentaService tipoDocService)
        {
            _tipoDocService = tipoDocService;
            _ventaService = ventaService;
        }


        public IActionResult Index()
        {
            //obtengo el Rol. Solo los administradores pueden hacer ventas
            ClaimsPrincipal claimUser = HttpContext.User;
            string Rol = claimUser.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).FirstOrDefault();
            if(Rol == "Administrador")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index","Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> ListaTipoDocumentoVenta()
        {
            List<TipoDocumentoVenta> listaTipoDoc = await _tipoDocService.Lista();
            return StatusCode(StatusCodes.Status200OK,listaTipoDoc);
        }

        [HttpGet]
        public async Task<IActionResult> ObtenerProductos(string busqueda) //funcion para la barra de busqueda en el form ventas. SE NECESITA USAR JAVASCRIPT
        {                                                                   //use select2 para hacer la barra de busqueda y el archivo Nueva_Venta.js
            List<Producto> listaProductos = await _ventaService.ObtenerProductos(busqueda);

            return StatusCode(StatusCodes.Status200OK, listaProductos);
        }

        [HttpPost]
        public async Task<IActionResult> RegistrarVenta([FromBody] VentaVM ventaVM) //SIn el [FROMBODY] No funciona
        {
            List<DetalleVenta> detalleVentaModelo = new List<DetalleVenta>();

            foreach (var detalleVM in ventaVM.DetalleVenta)
            {
                DetalleVenta detalleModelo = new DetalleVenta
                {
                    IdProducto = detalleVM.IdProducto,
                    MarcaProducto = detalleVM.Marca,
                    DescripcionProducto = detalleVM.Descripcion,
                    NombreProducto = detalleVM.NombreProducto,
                    Precio = detalleVM.Precio,
                    Total = detalleVM.Total,
                    Cantidad = detalleVM.Cantidad
                };
                detalleVentaModelo.Add(detalleModelo);
            }

            Venta ventaModelo = new Venta
            {
                IdTipoDocumentoVenta = ventaVM.IdTipoDocumentoVenta,
                DocumentoCliente = ventaVM.DocumentoCliente,
                NombreCliente = ventaVM.NombreCliente,
                SubTotal = ventaVM.SubTotal,
                ImpuestoTotal = ventaVM.ImpuestoTotal,
                Total = ventaVM.Total,
                DetalleVenta = detalleVentaModelo
                //la fecha la puse en el Service con el formato "yyyy-MM-dd HH:mm"
            };

            //obtengo el Id del usuario logeado
            ClaimsPrincipal claimUser = HttpContext.User;
            string idUser = claimUser.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).FirstOrDefault();

            ventaModelo.IdUsuario = Convert.ToInt32(idUser); //asigno el id


            Venta ventaCreada = await _ventaService.Registrar(ventaModelo); //registro la venta
            return StatusCode(StatusCodes.Status200OK, ventaCreada);
        }

        public IActionResult HistorialVenta()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Historial( string numeroVenta, string fechaInicio, string fechaFin)
        {
            List<Venta> historial = await _ventaService.Historial(numeroVenta, fechaInicio, fechaFin);
            return StatusCode(StatusCodes.Status200OK, historial);
        }
    }
}

AplicacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicacionWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicacionWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema de Ventas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ventas</a>
                            <div class="dropdown-menu">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Index">Crear venta</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="HistorialVenta">Historial</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Inventario</a>
                            <div class="dropdown-menu">
                                <a class ="dropdown-item" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                            </div>       
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img style="height:25px;" src="https://res.cloudinary.com/dmoinc30z/image/upload/v1705970290/j8nfnpj6qc3zhzhqdfzv.webp" class="rounded mx-auto" /><img />
                            </a>
                            <div class="dropdown-menu" style="right: 0;">
                                <a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Perfil</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Inicio" asp-action="CerrarSesion">Salir</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AplicacionWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>